export const ACTION_GET_DECKS = 'ACTION_GET_DECKS';
export const ACTION_GET_DECK = 'ACTION_GET_DECK';
export const ACTION_ADD_DECK = 'ACTION_ADD_DECK';
export const ACTION_ADD_CARD = 'ACTION_ADD_CARD';
export const ACTION_DELETE_ALL_DECKS = 'ACTION_DELETE_ALL_DECKS';
